# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "7.1.3"
gem "sqlite3", "~> 1.4"
gem "puma"
gem "rack-cors"
gem "bootsnap"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
end
